# Once you have finished making changes, use the "rebuild mathfly"
# command to enact them.
"pronunciation"   = "LyX"
"greek_prefix"    = "greek"
"symbol1_prefix"  = ""
"symbol2_prefix"  = "symbol"
"text_prefix"     = "text"
"number_prefix"   = ""
"accent_prefix"   = "accent"
"matrix_style"    = "matrix"
"max_matrix_size" = 10

# For a full list of the available key formatting options,
# see https://pythonhosted.org/dragonfly/actions.html
[misc_lyx_keys]
"math mode"                       = "c-m"
"new math line"                   = "escape:10, end, enter, c-m"
"fraction"                        = "a-m, f"
"over"                            = "cs-left, a-m, f, down"
"(super [script] | to the power)" = "caret"
"sub [script]"                    = "underscore"
"squared"                         = "caret, 2, right"
"cubed"                           = "caret, 3, right"
"inverse"                         = "caret, minus, 1, right"
"(parens | parentheses)"          = "a-m, lparen"
"square brackets"                 = "a-m, lbracket"
"curly brackets"                  = "a-m, lbrace"
"absolute"                        = "a-m, bar"
"add matrix row"                  = "a-m, w, i"
"(delete | remove) matrix row"    = "a-m, w, d"
"add matrix column"               = "a-m, c, i"
"(delete | remove) matrix column" = "a-m, c, d"


# Alternates between executing as text and executing as keys
[misc_lyx_commands]
"blank summation"        = "\\sum "
"summation"              = ["\\stackrelthree ", "down", "\\sum ", "down"]
"(summation | sum) to N" = ["\\stackrelthree ", "n, down", "\\sum ", "down"]
"blank product"          = "\\prod "
"product"                = ["\\stackrelthree ", "down", "\\prod ", "down"]
"product to N"           = ["\\stackrelthree ", "n, down", "\\prod ", "down"]
"limit"                  = ["\\underset \\lim ", "down"]
"blank limit"            = "\\lim "
"label above"            = "\\overset "
"label below"            = "\\underset "
"prime"                  = ["^\\prime ", "right"]
"degrees"                = ["^\\circ ", "right"]
"exponential"            = ["\\exp ", "a-m, lparen"]
"expectation"            = ["E", "a-m, lparen"]
"variance"               = ["Var", "a-m, lparen"]
#
"real numbers"           = ["\\mathbb R", "right"]
"complex numbers"        = ["\\mathbb C", "right"]
"integer numbers"        = ["\\mathbb Z", "right"]
"rational numbers"       = ["\\mathbb Q", "right"]
"natural numbers"        = ["\\mathbb N", "right"]


[greek_letters]
"alpha"   = "alpha"
"beater"  = "beta"
"gamma"   = "gamma"
"delta"   = "delta"
"epsilon" = "varepsilon"
"zita"    = "zeta"
"eater"   = "eta"
"theta"   = "theta"
"iota"    = "iota"
"kappa"   = "kappa"
"lambda"  = "lambda"
"mu"      = "mu"
"new"     = "nu"
"zee"     = "xi"
"pie"     = "pi"
"row"     = "rho"
"sigma"   = "sigma"
"tau"     = "tau"
"upsilon" = "upsilon"
"phi"     = "phi"
"chi"     = "chi"
"sigh"    = "psi"
"omega"   = "omega"


[tex_symbols1]
# operators
"square root"                  = "sqrt"
"[generic] root"               = "root"
"integral"                     = "int"
"double integral"              = "iint"
"triple integral"              = "iiint"
"times"                        = "times"
"divide"                       = "div"
"stop"                         = "cdot"
"plus or minus"                = "pm"
"partial"                      = "partial"
"infinity"                     = "infty"
"(nice frack | nice fraction)" = "nicefrac"
"binomial"                     = "binom"
"vector nabla"                 = "nabla"
# trig
"sine"                         = "sin"
"cosine"                       = "cos"
"tangent"                      = "tan"
"secant"                       = "sec"
"cosecant"                     = "csc"
"cotangent"                    = "cot"
"arc sine"                     = "arcsin"
"arc cosine"                   = "arccos"
"arc tan"                      = "arctan"
"hyperbolic sine"              = "sinh"
"hyperbolic cosine"            = "cosh"
"hyperbolic cotangent"         = "coth"
"hyperbolic tangent"           = "tanh"
# functions
"argument"                     = "arg"
"degree"                       = "deg"
"determinant"                  = "det"
"dimension"                    = "dim"
"(natural (log | logarithm) | log natural)" = "ln"
"logarithm"                    = "log"
"maximum"                      = "max"
"minimum"                      = "min"
"(modulo | modulus)"           = "bmod"
"infimum"                      = "inf"
"supremum"                     = "sup"
"probability"                  = "Pr"
# relations
"there exists"                 = "exists"
"member"                       = "in"
"for all"                      = "forall"
"[is] not equal [to]"          = "neq"
"[is] greater [than] [or] equal [to]" = "geq"
"[is] less [than] [or] equal [to]" = "leq"
"[is] approximately [equal] [to]" = "approx"
"proportional [to]"            = "propto"
"preference less [than]"       = "prec"
"preference less equals"       = "preceq"
"preference greater [than]"    = "succ"
"preference greater equal"     = "succeq"
# sets
"empty set"                    = "emptyset"
"subset"                       = "subset"
"superset"                     = "supset"
"strict subset"                = "subsetneq"
"strict superset"              = "supsetneq"
"intersection"                 = "cap"
"union"                        = "cup"
# logic
"logic and"                    = "land"
"logic or"                     = "lor"
"logic not"                    = "lnot"
#
"left arrow"                   = "leftarrow"
"right arrow"                  = "rightarrow"
"up arrow"                     = "uparrow"
"down arrow"                   = "downarrow"
"left right arrow"             = "leftrightarrow"
"maps to"                      = "mapsto"
"oh plus"                      = "oplus"
"oh times"                     = "otimes"
"big oh plus"                  = "bigoplus"
"big oh times"                 = "bigotimes"
#
"dot dot dot"                  = "dots"
"diagonal dots"                = "ddots"
"horizontal dots"              = "cdots"
"vertical dots"                = "vdots"

# Require a prefix, as these (I think) are fairly uncommon
# feel free to move this stuff around.
[tex_symbols2]
"GCD"                        = "gcd"
"cat hom"                    = "hom"
"kernel"                     = "ker"
"unit"                       = "unitone"
"unit two"                   = "unittwo"
"unit fraction "             = "unitfrac"
"text fraction"              = "tfrac"
"display fraction"           = "dfrac"
"continued fraction"         = "cfrac"
"continued fraction (left)"  = "cfracleft"
"continued fraction (right)" = "cfracright"
"text binomial"              = "tbinom"
"display binomial"           = "dbinom"

[text_modes]
"roman"      = "mathrm"
"bold"       = "mathbf"
"sans serif" = "mathsf"
"italic"     = "mathit"
"typewriter" = "mathtt"
# math fonts
# "normal" = "textrm"
"(beebee|blackboard bold | blackboard)" = "mathbb"
# "bold symbol" = "boldsymbol"
# "fraktur" = "mathfrak"
# "calligraphic" = "mathcal"
# "formal script" = "mathscr"

[accents]
"hat"        = "h"
"tilde"      = "ampersand"
"dot"        = "dot"
"double dot" = "dquote"
"bar"        = "minus"
"vector"     = "v"

[denominators]
"(half | halves)"      = 2
"(third | thirds)"     = 3
"(quarter | quarters | fourth | fourths)" = 4
"(fifth | fifths)"     = 5
"(sixth | sixths)"     = 6
"(seventh | sevenths)" = 7
"(eighth | eighths)"   = 8
"(ninth | ninths)"     = 9
"(tenth | tenths)"     = 10